// src/app/page.tsx
import Link from "next/link";
import { GraduationCap, Sparkles, BookOpen, Shield, Users, ArrowRight, CheckCircle } from "lucide-react";

export default function LandingPage() {
  const features = [
    { icon: Sparkles,    title: "AI Prompt Generator",    desc: "Generate precision-engineered prompts that produce complete 90–120 page NOUN-compliant research projects." },
    { icon: BookOpen,    title: "5-Chapter Structure",    desc: "Enforce NOUN's academic constitution: Introduction → Literature Review → Methodology → Analysis → Conclusion." },
    { icon: Users,       title: "Supervisor Workflow",    desc: "Invite supervisors, track chapter approvals, inline comments, and real-time collaboration." },
    { icon: Shield,      title: "Academic Integrity",     desc: "AI-generated content follows strict scholarly guidelines — objective voice, APA citations, no plagiarism." },
  ];

  const stats = [
    { val: "109+", label: "Pages per project" },
    { val: "14",   label: "Charts & figures"  },
    { val: "9",    label: "Data tables"        },
    { val: "55+",  label: "APA references"     },
  ];

  return (
    <div className="min-h-screen bg-[#0a0d12] text-[#e8edf5]">
      {/* Background */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute inset-0 opacity-40"
          style={{ backgroundImage: "linear-gradient(rgba(201,168,76,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(201,168,76,.03) 1px,transparent 1px)", backgroundSize: "50px 50px" }} />
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-[rgba(201,168,76,.05)] rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-[rgba(46,204,143,.04)] rounded-full blur-3xl" />
      </div>

      {/* Nav */}
      <nav className="sticky top-0 z-50 bg-[rgba(10,13,18,.9)] backdrop-blur-xl border-b border-[#1e2a3a]">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#c9a84c] to-[#8a6f32] flex items-center justify-center">
              <GraduationCap className="w-5 h-5 text-[#0a0d12]" />
            </div>
            <span className="font-bold text-white font-serif">
              ProjectAssistant<span className="text-[#c9a84c]">AI</span>
            </span>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/auth/login"
              className="px-4 py-2 text-sm font-medium text-[#8a9bb5] hover:text-white transition-colors">
              Sign In
            </Link>
            <Link href="/auth/signup"
              className="px-4 py-2 bg-gradient-to-r from-[#c9a84c] to-[#8a6f32] text-[#0a0d12] font-bold text-sm rounded-xl hover:shadow-[0_8px_30px_rgba(201,168,76,.3)] transition-all">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      <main className="relative z-10">
        {/* Hero */}
        <section className="max-w-4xl mx-auto px-6 pt-24 pb-16 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[rgba(201,168,76,.1)] border border-[rgba(201,168,76,.25)] text-[#c9a84c] text-xs font-semibold mb-7">
            <span className="w-1.5 h-1.5 rounded-full bg-[#c9a84c] animate-pulse" />
            Nigeria&apos;s Premier Academic AI Platform
          </div>
          <h1 className="font-serif text-5xl md:text-6xl font-bold leading-tight mb-6">
            Complete Research Projects,{" "}
            <span className="italic text-[#c9a84c]">Generated by AI</span>
          </h1>
          <p className="text-lg text-[#8a9bb5] max-w-2xl mx-auto mb-10 leading-relaxed">
            Generate 90–120 page NOUN-compliant research projects with all 5 chapters, 
            charts, tables, APA references, and appendices — exported as professional Word documents.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap">
            <Link href="/auth/signup"
              className="inline-flex items-center gap-2.5 px-7 py-3.5 bg-gradient-to-r from-[#c9a84c] to-[#8a6f32] text-[#0a0d12] font-bold text-base rounded-xl hover:shadow-[0_12px_40px_rgba(201,168,76,.4)] hover:-translate-y-0.5 transition-all">
              <Sparkles className="w-5 h-5" />
              Start Generating Free
            </Link>
            <Link href="/auth/login"
              className="inline-flex items-center gap-2 px-6 py-3.5 border border-[#1e2a3a] text-[#8a9bb5] hover:text-white hover:border-[#2a3a52] rounded-xl text-base font-medium transition-all">
              Sign In <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </section>

        {/* Stats */}
        <section className="max-w-4xl mx-auto px-6 pb-16">
          <div className="grid grid-cols-4 divide-x divide-[#1e2a3a] bg-[#111620] border border-[#1e2a3a] rounded-2xl overflow-hidden">
            {stats.map(s => (
              <div key={s.label} className="py-6 text-center hover:bg-[#181f2e] transition-colors">
                <div className="text-3xl font-bold text-[#c9a84c] font-serif mb-1">{s.val}</div>
                <div className="text-xs text-[#4a5a72]">{s.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Features */}
        <section className="max-w-5xl mx-auto px-6 pb-20">
          <h2 className="text-3xl font-bold text-white font-serif text-center mb-12">
            Everything you need for academic excellence
          </h2>
          <div className="grid md:grid-cols-2 gap-5">
            {features.map(f => {
              const Icon = f.icon;
              return (
                <div key={f.title}
                  className="bg-[#111620] border border-[#1e2a3a] rounded-xl p-6 hover:border-[#2a3a52] hover:-translate-y-0.5 transition-all">
                  <div className="w-11 h-11 rounded-xl bg-[rgba(201,168,76,.1)] border border-[rgba(201,168,76,.2)] flex items-center justify-center mb-4">
                    <Icon className="w-5 h-5 text-[#c9a84c]" />
                  </div>
                  <h3 className="font-bold text-white mb-2">{f.title}</h3>
                  <p className="text-sm text-[#4a5a72] leading-relaxed">{f.desc}</p>
                </div>
              );
            })}
          </div>
        </section>

        {/* NOUN Compliance callout */}
        <section className="max-w-3xl mx-auto px-6 pb-20">
          <div className="bg-gradient-to-br from-[rgba(201,168,76,.08)] to-transparent border border-[rgba(201,168,76,.2)] rounded-2xl p-8">
            <h3 className="text-xl font-bold text-white font-serif mb-4">NOUN-Compliant by Default</h3>
            <div className="grid sm:grid-cols-2 gap-3">
              {[
                "Times New Roman 12pt, double-spaced",
                "APA 7th Edition citations",
                "5-chapter structure enforced",
                "Minimum 50+ scholarly references",
                "All hypothesis tests with exact statistics",
                "Abstract max 400 words, single-spaced",
                "List of Tables, Figures & Abbreviations",
                "Complete Appendices (Questionnaire + Guides)",
              ].map(item => (
                <div key={item} className="flex items-center gap-2.5 text-sm text-[#8a9bb5]">
                  <CheckCircle className="w-4 h-4 text-[#2ecc8f] flex-shrink-0" />
                  {item}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="max-w-2xl mx-auto px-6 pb-24 text-center">
          <h2 className="text-3xl font-bold text-white font-serif mb-4">Ready to generate your project?</h2>
          <p className="text-[#8a9bb5] mb-8">Join thousands of Nigerian students who have used ProjectAssistantAI to complete their research.</p>
          <Link href="/auth/signup"
            className="inline-flex items-center gap-2.5 px-8 py-4 bg-gradient-to-r from-[#c9a84c] to-[#8a6f32] text-[#0a0d12] font-bold text-base rounded-xl hover:shadow-[0_12px_40px_rgba(201,168,76,.4)] hover:-translate-y-0.5 transition-all">
            <GraduationCap className="w-5 h-5" />
            Create Free Account
          </Link>
        </section>
      </main>

      <footer className="border-t border-[#1e2a3a] py-8">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <p className="font-serif font-bold text-white mb-1">
            ProjectAssistant<span className="text-[#c9a84c]">AI</span>
          </p>
          <p className="text-xs text-[#2a3a52]">
            Nigeria&apos;s Premier Academic AI Platform |{" "}
            <a href="https://www.projectassistantai.com.ng" className="text-[#c9a84c] hover:text-[#e8c76a] transition-colors">
              www.projectassistantai.com.ng
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
